apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
        - name: service3
          image: ko://my-microservices/service3
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: service3-service
spec:
  selector:
    app: service3
  ports:
    - port: 80
      targetPort: 8083
