apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-service3
  labels:
    app: services-service3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: services-service3
  template:
    metadata:
      labels:
        app: services-service3
    spec:
      containers:
      - name: services-service3
        image: simret101/services_service3:latest
        ports:
        - containerPort: 8083
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: services-service3
spec:
  selector:
    app: services-service3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP
